# Generated by Django 6.1 on 2026-08-31 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Mã tài sản')),
                ('asset_name', models.CharField(max_length=200, verbose_name='Tên thiết bị')),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Máy in'), ('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('server', 'Server'), ('other', 'Khác')], max_length=20, verbose_name='Loại thiết bị')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Số Serial')),
                ('assigned_user_name', models.CharField(blank=True, max_length=150, verbose_name='Tên người sử dụng')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Ngày mua')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='Hết hạn bảo hành')),
                ('status', models.CharField(choices=[('in_use', 'Đang sử dụng'), ('in_stock', 'Trong kho'), ('repair', 'Đang sửa chữa'), ('retired', 'Đã thanh lý')], default='in_stock', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Người sử dụng')),
            ],
            options={
                'verbose_name': 'Tài sản CNTT',
                'verbose_name_plural': 'Tài sản CNTT',
                'ordering': ['-created_at'],
            },
        ),
    ]
