# Generated by Django 6.1 on 2026-09-01 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Nội dung')),
                ('meeting_type', models.CharField(choices=[('standup', 'Daily Standup'), ('team', 'Họp Team'), ('all_hands', 'All Hands'), ('client', 'Họp với Khách hàng'), ('review', 'Sprint Review'), ('training', 'Đào tạo'), ('other', 'Khác')], default='team', max_length=20, verbose_name='Loại cuộc họp')),
                ('location', models.CharField(blank=True, help_text='Ví dụ: Phòng họp A, Google Meet, Zoom...', max_length=200, verbose_name='Địa điểm')),
                ('start_time', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Kết thúc')),
                ('priority', models.CharField(choices=[('normal', 'Bình thường'), ('important', 'Quan trọng'), ('urgent', 'Khẩn cấp')], default='normal', max_length=15, verbose_name='Mức độ')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Lặp lại hàng tuần')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Người tổ chức')),
            ],
            options={
                'verbose_name': 'Cuộc họp',
                'verbose_name_plural': 'Cuộc họp',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('accepted', 'Tham gia'), ('declined', 'Từ chối')], default='pending', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người tham dự',
                'verbose_name_plural': 'Người tham dự',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
