# Generated by Django 6.1 on 2026-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pinned', '-created_at'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'Chung'), ('new_employee', 'Nhân viên mới'), ('company_update', 'Cập nhật công ty'), ('event', 'Sự kiện'), ('policy', 'Chính sách')], default='general', max_length=20, verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim lên đầu'),
        ),
    ]
