# Generated by Django 6.1 on 2026-08-31 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Đăng nhập thành công'), ('LOGIN_FAILURE', 'Đăng nhập thất bại'), ('LOGOUT', 'Đăng xuất'), ('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('VIEW', 'Xem'), ('ASSIGN', 'Phân công')], max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Loại đối tượng')),
                ('resource_id', models.CharField(blank=True, max_length=50, verbose_name='ID đối tượng')),
                ('resource_name', models.CharField(blank=True, max_length=200, verbose_name='Tên đối tượng')),
                ('description', models.TextField(blank=True, verbose_name='Chi tiết')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
