# Generated by Django 6.1 on 2026-09-01 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Ví dụ: Tháng 8/2026', max_length=50, verbose_name='Kỳ lương')),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Lương cơ bản')),
                ('allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phụ cấp')),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thưởng')),
                ('deduction', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Khấu trừ (BHXH, thuế...)')),
                ('net_salary', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Thực lãnh')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('sent', 'Đã gửi'), ('confirmed', 'Đã xác nhận')], default='draft', max_length=15, verbose_name='Trạng thái')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phiếu lương',
                'verbose_name_plural': 'Phiếu lương',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
